micronaut:
    application:
        name: example
    server:
        port: 8090
    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
endpoints:
    prometheus:
        sensitive: false
asterank:
    limit: 10
